import ErdosProblems.Erdos1.DyadicAlgebra

/-! # Exact flow through a dyadic block -/

namespace Erdos1

/-- The real coefficient vector generated by an incoming flow `s`, with zero internal output. -/
noncomputable def openResponse : (h : ℕ) → ℝ → DyadicVertex h → ℝ
  | 0, s => ![s / 2, s / 4, 3 * s / 8]
  | h + 1, s =>
    let l := openResponse h s
    let r := openResponse h (exitFlow l)
    Sum.elim (Sum.elim l r) (fun _ => (l (rootVertex h) + r (rootVertex h)) / 2)

theorem blockAction_openResponse (h : ℕ) (s : ℝ) :
    blockAction (openResponse h s) s = 0 := by
  induction h generalizing s with
  | zero =>
    funext i
    fin_cases i <;> simp [blockAction, openResponse] <;> ring
  | succ h ih =>
    funext i
    rcases i with ((i | i) | u)
    · exact congrFun (ih s) i
    · exact congrFun (ih (exitFlow (openResponse h s))) i
    · simp [blockAction, openResponse, leftCoeffs, rightCoeffs]
      ring

theorem openResponse_root (h : ℕ) (s : ℝ) :
    openResponse h s (rootVertex h) = (3 / 8) * dyadicDensity h * s := by
  induction h generalizing s with
  | zero => simp [openResponse, rootVertex]; ring
  | succ h ih =>
    have hflow (t : ℝ) : exitFlow (openResponse h t) =
        (1 - (3 / 8) * dyadicDensity h) * t := by
      have hh := sum_blockAction (openResponse h t) t
      simp only [blockAction_openResponse, Pi.zero_apply, Finset.sum_const_zero, ih] at hh
      linarith
    change (openResponse h s (rootVertex h) +
      openResponse h (exitFlow (openResponse h s)) (rootVertex h)) / 2 = _
    rw [ih, ih, hflow, dyadicDensity_succ]
    ring

theorem openResponse_exit (h : ℕ) (s : ℝ) :
    exitFlow (openResponse h s) = (1 - (3 / 8) * dyadicDensity h) * s := by
  have hh := sum_blockAction (openResponse h s) s
  simp only [blockAction_openResponse, Pi.zero_apply, Finset.sum_const_zero,
    openResponse_root] at hh
  linarith

end Erdos1
